### PR TITLE
Add PR created and review comments

### LINKED ISSUE #1: Feature: Add PRs raised and PR comments
## Feature

Add PRs raised and PR comments

## Tasks

* Extend SQL schema
* Add columns to SQL function for query
* Update insert function
* Update query function
* Write migration script for existing deployment on OFC to add columns

### PR DESCRIPTION
**Pull request by burtonr**
This change adds 2 additional columns to the results
These new columns will provide better insight into
Pull Request activity for number created, and review comments
regular PR comments are already tracked as part of the
issue comments. Review comments are the comments left
in-line on a PRs change

Signed-off-by: Burton Rheutan <rheutan7@gmail.com>

This resolves #1 

A new folder is added for storing the SQL function's change history.
Within the SQL folder is a `migration` folder where the files are named `yyyyMMdd-change-description.sql`

**This has not yet been fully tested**

### CODE REVIEW

**Comment by burtonr** [comment]
I've tried for a couple hours trying to get this to run locally, but I am unable to get the leaderboard-page to load at all. 

If there could be a section on how to deploy this app, I could test it, but I was unable to figure it out myself.

**Comment by alexellis** [comment]
I don't feel good about merging this without e2e testing.

Why don't you deploy to your own OpenFaaS Cloud account?

You'll need to:

* use your master branch in your fork
* setup temporary postgres on DO or somewhere else like a 2-5USD VPS
* create the initial tables
* create the secrets and seal them
* trigger a build and then hook up a webhook

**Comment by alexellis** [comment]
> This has not yet been fully tested

What has been tested?

Alex

**Comment by alexellis** [comment]
I spent my morning working through testing the existing code locally, so that you can do the same with your PR. All the instructions are outlined in the README.md file (which also creates a rebase conflict on your PR)

https://github.com/alexellis/leaderboard-app

Let me know if you have problems and _do reach out on Slack_ to me/the community.

**Comment by burtonr** [comment]
@alexellis apologies for the delays. Life got in the way a bit. 

Thank you for updating the readme to include local setup. I was able to get this running in order to test it fully. I did end up having to make a minor change in the `App.vue` that I missed originally.

Here is a screenshot of the final result:
Screenshot from 2019-03-23 11-15-41

**Comment by alexellis** [comment]
That looks great. Do you have the steps needed for Vue? How was the local development?

**Comment by burtonr** [comment]
Thanks! I just had a little trouble with the database connection. Forgot there were environment variables to update. Had to change `postgres_db`, `postgres_port`, and `postgres_sslmode: disable` before it would work.
For the changes to Vue to be reflected, I had to go into the `client` directory, and run `npm run build`, then I could re-build the function and deploy.

**Comment by nico-kn** [comment]
@burtonr are you still pursuing this? Would love to use the PR feature :)

**Comment by burtonr** [comment]
@nico-kn Since this has been waiting for approval for over a year, It doesn't look like it will get approved and merged as there are now conflicting files. Unfortunately, the forked repo was deleted as I cleaned out old projects, so I wouldn't be able to make any updates.

I would have no problem with you (or someone) taking the changes listed here and implementing them on a different fork.

**Pull request closed without merging**
